name: Deploy Helm Chart

on:
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.27.1/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl        

      - name: Set up Kubernetes context
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_SECRET }}
        run: |
          echo "$KUBECONFIG_DATA" | base64 --decode > $HOME/.kube/config

      - name: Setup Helm
        uses: azure/setup-helm@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Specify the AWS region of your EKS cluster

      - name: Deploy Helm Chart
        run: |
          helm repo add myrepo https://myrepo.example.com/charts
          helm repo update
          helm upgrade --install myrelease myrepo/mychart --namespace mynamespace --values values.yaml
